import type { Metadata } from "next";
import "./globals.css";
import { Delicious_Handrawn } from "next/font/google";
import Navbar from "@/components/common/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const delicious_handrawn = Delicious_Handrawn({
  weight: ["400"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${delicious_handrawn.className} bg-background text-foreground min-h-screen`}
      >
        <div>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
